/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-background": "#dfe2ef",
        "tertiary-fixed-dim": "#ffb3ad",
        "secondary-container": "#00b954",
        "surface-variant": "#31353e",
        "on-primary-fixed-variant": "#004395",
        "surface-container-low": "#181c25",
        "outline-variant": "#424754",
        "on-primary": "#002e6a",
        "inverse-primary": "#005ac2",
        "on-tertiary-fixed-variant": "#930013",
        "on-secondary": "#003915",
        "tertiary-fixed": "#ffdad7",
        "surface-container": "#1c2029",
        "secondary-fixed-dim": "#4ae176",
        "on-surface-variant": "#c2c6d6",
        "surface-dim": "#0f131c",
        "on-secondary-container": "#004119",
        "primary-fixed": "#d8e2ff",
        "surface-container-lowest": "#0a0e17",
        "surface-container-high": "#262a33",
        "on-surface": "#dfe2ef",
        "surface": "#0f131c",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#6bff8f",
        "on-secondary-fixed-variant": "#005321",
        "secondary": "#4ae176",
        "on-primary-container": "#00285d",
        "on-primary-fixed": "#001a42",
        "error-container": "#93000a",
        "on-tertiary-container": "#5c0008",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#410004",
        "outline": "#8c909f",
        "tertiary-container": "#ff5451",
        "on-error": "#690005",
        "surface-bright": "#353943",
        "inverse-on-surface": "#2c303a",
        "tertiary": "#ffb3ad",
        "on-secondary-fixed": "#002109",
        "inverse-surface": "#dfe2ef",
        "primary-container": "#4d8eff",
        "background": "#0f131c",
        "surface-container-highest": "#31353e",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary": "#68000a",
        "primary": "#adc6ff",
        "surface-tint": "#adc6ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "title-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"]
      },
    },
  },
  plugins: [],
}
